'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const http=require('node:http');
const {Store}=require('../store');
const {createApp}=require('../server');

const familyFixture={name:'Everyday Explained',tier:'A',countries:['United States','United Kingdom'],audience:'Curious adults looking for clear everyday explanations.',niche:'Original illustrated explanations',spanishLocale:'es-419',englishLocale:'en-US',timezone:'Asia/Karachi',monthlyBudget:120.25,cadence:2,format:'long-form'};
const contentFixture={title:'Why a well-organized room can still feel slow',kind:'factual',angle:'Use an original scene to demonstrate how movement affects a daily task.',hook:'Everything has a place. Why does the task still take so many trips?',script:'An organized room can still make a simple task feel awkward. Imagine moving between a cupboard, a table, and a sink. In our original illustration we follow one task and compare the different paths. The example does not claim one layout works for everybody. It shows how you can observe your own routine, identify an extra trip, and try a small change. The payoff is a clearer way to examine a familiar space.',sources:[{title:'Creator evidence fixture',url:'https://example.com/fixture',permission:'permitted',notes:'Test evidence supplied by the creator; this is a fixture, not actual research.'}],rightsConfirmed:true};
function memory(t){const s=new Store(':memory:');t.after(()=>s.close());return s;}
function family(s,extra={}){return s.saveFamily({...structuredClone(familyFixture),...extra});}
function draft(s,f,extra={}){return s.saveContent({...structuredClone(contentFixture),familyId:f.id,...extra});}
function approve(s,c){s.reviewContent(c.id,{revision:c.revision,action:'submit'});return s.reviewContent(c.id,{revision:c.revision,action:'approve'});}
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'control-room-test-'));t.after(()=>{
  const resolved=path.resolve(dir),parent=path.resolve(os.tmpdir());
  assert.equal(path.dirname(resolved),parent);assert.ok(path.basename(resolved).startsWith('control-room-test-'));
  fs.rmSync(resolved,{recursive:true,force:true});
});return dir;}

test('family creates three honest language slots and exact budget cents',t=>{const s=memory(t),f=family(s);assert.equal(f.budgetCents,12025);assert.deepEqual(f.channels.map(c=>c.language),['en','es','it']);assert.ok(f.channels.every(c=>c.connection==='not_connected'));assert.equal(s.state().families.length,1);});
test('family inputs reject invalid countries, cadence, dates and spend',t=>{const s=memory(t);for(const invalid of [{countries:[]},{countries:['']},{timezone:'Imaginary/City'},{monthlyBudget:-1},{monthlyBudget:1.001},{cadence:1.5},{cadence:0},{tier:'universal'},{englishLocale:'it'}])assert.throws(()=>family(s,invalid));assert.equal(s.state().families.length,0);});
test('duplicate family names are rejected without partial writes',t=>{const s=memory(t);family(s);assert.throws(()=>family(s,{name:'everyday explained'}),{status:409});assert.equal(s.state().families.length,1);assert.equal(s.state().events.length,1);});
test('family updates reject stale versions and archive preserves drafts',t=>{const s=memory(t),f=family(s),c=draft(s,f);const updated=s.saveFamily({...familyFixture,name:'New family name',revision:1},f.id);assert.equal(updated.revision,2);assert.throws(()=>s.saveFamily({...familyFixture,revision:1},f.id),{status:409});s.archiveFamily(f.id,{revision:2,archived:true});assert.equal(s.content(c.id).title,c.title);assert.throws(()=>s.saveContent({...c,script:'Changed script'},c.id),{status:409});s.archiveFamily(f.id,{revision:3,archived:false});assert.equal(s.family(f.id).archived,false);});
test('active family capacity is enforced on create and restore',t=>{const s=memory(t),f=family(s);for(let i=1;i<15;i++)family(s,{name:`Family ${i}`});assert.throws(()=>family(s,{name:'Sixteenth'}));s.archiveFamily(f.id,{revision:1,archived:true});family(s,{name:'Replacement'});assert.throws(()=>s.archiveFamily(f.id,{revision:2,archived:false}));assert.equal(s.families().filter(f=>!f.archived).length,15);});
test('incomplete drafts save but cannot bypass review',t=>{const s=memory(t),c=draft(s,family(s),{script:'',angle:'',sources:[],rightsConfirmed:false});assert.equal(c.state,'draft');assert.throws(()=>s.reviewContent(c.id,{revision:1,action:'approve'}),{status:409});assert.throws(()=>s.reviewContent(c.id,{revision:1,action:'submit'}));assert.equal(s.content(c.id).state,'draft');assert.throws(()=>s.queueStoryboard(c.id,{revision:1}),{status:409});});
test('factual drafts require reviewed sources; original fiction still requires attestation',t=>{const s=memory(t),f=family(s);for(const extra of [{sources:[]},{sources:[{...contentFixture.sources[0],permission:'unreviewed'}]},{sources:[{...contentFixture.sources[0],notes:''}]},{kind:'fiction',sources:[],rightsConfirmed:false}]){const c=draft(s,f,extra);assert.throws(()=>s.reviewContent(c.id,{revision:1,action:'submit'}));}const fictional=draft(s,f,{kind:'fiction',sources:[]});assert.equal(approve(s,fictional).state,'approved');});
test('title length is checked before upstream normalization and source URLs are bounded',t=>{const s=memory(t),f=family(s);assert.throws(()=>draft(s,f,{title:'a'.repeat(101)}));for(const url of ['javascript:alert(1)','file:///etc/passwd','https://user:password@example.com'])assert.throws(()=>draft(s,f,{sources:[{...contentFixture.sources[0],url}]}));assert.throws(()=>draft(s,f,{script:'bad\0script'}));});
test('draft identity cannot move between families and stale saves fail',t=>{const s=memory(t),f=family(s),other=family(s,{name:'Other'}),c=draft(s,f);assert.throws(()=>s.saveContent({...c,familyId:other.id},c.id));s.saveContent({...c,title:'A new original title'},c.id);assert.throws(()=>s.saveContent(c,c.id),{status:409});assert.equal(s.content(c.id).familyId,f.id);});
test('editing approved content invalidates approval, scenes and editions',t=>{const s=memory(t),c=approve(s,draft(s,family(s)));s.queueStoryboard(c.id,{revision:1});s.processNextJob();assert.equal(s.content(c.id).scenes.length,6);const edited=s.saveContent({...c,title:'A newly reviewed version'},c.id);assert.equal(edited.revision,2);assert.equal(edited.state,'draft');assert.equal(edited.approvedAt,null);assert.deepEqual(edited.scenes,[]);assert.ok(edited.editions.every(e=>e.state==='not_started'));});
test('duplicate planning jobs reuse the same result and preserve all script words',t=>{const s=memory(t),c=approve(s,draft(s,family(s)));const a=s.queueStoryboard(c.id,{revision:1}),b=s.queueStoryboard(c.id,{revision:1});assert.equal(a.id,b.id);s.processNextJob();assert.equal(s.processNextJob(),null);assert.equal(s.queueStoryboard(c.id,{revision:1}).id,a.id);const saved=s.content(c.id);assert.equal(saved.scenes.map(x=>x.narration).join(' '),c.script);assert.deepEqual(saved.editions.map(e=>e.state),['script_ready','awaiting_translation','awaiting_translation']);assert.equal(s.state().jobs[0].status,'completed');assert.equal(s.exportContent(c.id).limitations.length,3);});
test('edited or archived work cancels queued storyboard jobs',t=>{const s=memory(t),f=family(s),c=approve(s,draft(s,f));s.queueStoryboard(c.id,{revision:1});s.saveContent({...c,title:'Changed before worker'},c.id);s.processNextJob();assert.equal(s.state().jobs[0].status,'cancelled');const next=approve(s,draft(s,f));s.queueStoryboard(next.id,{revision:1});s.archiveFamily(f.id,{revision:1,archived:true});s.processNextJob();assert.ok(s.state().jobs.every(j=>j.status==='cancelled'));});
test('unexpected planning errors become visible failed jobs instead of endless retries',t=>{const s=memory(t),c=approve(s,draft(s,family(s)));s.queueStoryboard(c.id,{revision:1});const read=s.content;s.content=()=>{throw new Error('Injected worker failure');};s.processNextJob();s.content=read;assert.equal(s.state().jobs[0].status,'failed');assert.equal(s.processNextJob(),null);assert.equal(s.content(c.id).scenes.length,0);});
test('SQLite persists records and recovers an interrupted job on restart',t=>{const filename=path.join(temp(t),'workspace.sqlite');let s=new Store(filename);const c=approve(s,draft(s,family(s)));s.queueStoryboard(c.id,{revision:1});s.db.exec("UPDATE jobs SET status='running'");s.close();s=new Store(filename);try{assert.equal(s.content(c.id).state,'approved');assert.equal(s.state().jobs[0].status,'queued');s.processNextJob();assert.equal(s.state().jobs[0].status,'completed');}finally{s.close();}});

test('HTTP boundary, UI files and complete API workflow',async t=>{
  const {server,store}=createApp({dataFile:':memory:',worker:false});
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const initial=await (await fetch(`${base}/api/state`)).json();
  async function request(route,body,method='POST',headers={}){return fetch(base+route,{method,headers:{'Content-Type':'application/json','X-Local-Token':initial.token,...headers},body:typeof body==='string'?body:JSON.stringify(body)});}
  await t.test('local health and static files load with protection headers',async()=>{const response=await fetch(base);assert.equal(response.status,200);assert.match(response.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.match(await response.text(),/Content studio/);for(const file of ['/app.js','/style.css'])assert.equal((await fetch(base+file)).status,200);assert.equal((await (await fetch(base+'/api/health')).json()).mode,'local-planning');});
  await t.test('cross-origin, spoofed host and missing token writes are rejected',async()=>{assert.equal((await request('/api/families',familyFixture,'POST',{'X-Local-Token':''})).status,403);assert.equal((await request('/api/families',familyFixture,'POST',{Origin:'https://evil.example'})).status,403);const spoofed=await new Promise((resolve,reject)=>{http.get(base+'/api/state',{headers:{Host:'evil.example'}},response=>{response.resume();resolve(response.statusCode);}).on('error',reject);});assert.equal(spoofed,403);assert.equal(store.families().length,0);});
  await t.test('malformed, non-object, wrong content type and large requests cannot write',async()=>{for(const body of ['{','null','[]'])assert.equal((await request('/api/families',body)).status,400);assert.equal((await request('/api/families',familyFixture,'POST',{'Content-Type':'text/plain'})).status,415);assert.equal((await request('/api/families',JSON.stringify({text:'x'.repeat(270000)}))).status,413);assert.equal(store.families().length,0);});
  await t.test('data and vendor files cannot be served through arbitrary paths',async()=>{for(const route of ['/data/control-room.sqlite','/vendor/agent-reach/LICENSE','/../store.js','/api/missing'])assert.equal((await fetch(base+route)).status,404);});
  await t.test('create, save, review, plan and export through actual routes',async()=>{const fr=await request('/api/families',familyFixture);assert.equal(fr.status,200);const f=await fr.json();const cr=await request('/api/content',{...contentFixture,familyId:f.id});assert.equal(cr.status,200);const c=await cr.json();for(const action of ['submit','approve'])assert.equal((await request(`/api/content/${c.id}/review`,{revision:1,action})).status,200);assert.equal((await request(`/api/content/${c.id}/storyboard`,{revision:1})).status,200);store.processNextJob();const exported=await fetch(`${base}/api/content/${c.id}/export`);assert.match(exported.headers.get('content-disposition'),/attachment/);assert.equal((await exported.json()).content.scenes.length,6);});
});
